export const GENRES = {
    "2D": 1,
    "3D": 1,
    "4X": 1,
    "Action": 1,
    "Adventure": 1,
    "Aircraft": 1,
    "Arcade": 1,
    "Artillery": 1,
    "Athletics": 1,
    "Auto": 1,
    "Battle": 1,
    "Beat-'Em-Up": 1,
    "Biking": 1,
    "Board": 1,
    Card: 0.75,
    "Career": 1,
    "Combat": 1,
    "Command": 1,
    "Compilation": 1,
    "Defense": 1,
    "Edutainment": 1,
    "Fighting": 1,
    "First-Person": 1,
    "Fishing": 1,
    "FPS": 1,
    "Future": 1,
    "Gambling": 1,
    "Gun": 1,
    "Hidden": 1,
    "Horizontal": 1,
    "Hunting": 1,
    "Individual": 1,
    JRPG: 3,
    "Life": 1,
    "Light": 1,
    "Linear": 1,
    "Logic": 1,
    "Management": 1,
    "Marine": 1,
    "Matching": 1,
    "Metroidvania": 1,
    "Miscellaneous": 1,
    MMORPG: 10,
    "MOBA": 1,
    "Novel": 1,
    "Object": 1,
    "Open-World": 1,
    "Party": 1,
    "Person": 1,
    "Pinball": 1,
    "Platformer": 1,
    "Point-and-Click": 1,
    Puzzle: 1,
    "Racing": 1,
    "Rail": 1,
    "Real-Time": 1,
    "Rhythm": 1,
    "Roguelike": 1,
    "RPG": 1,
    "RTS": 1,
    "Sandbox": 1,
    "Shoot-'Em-Up": 1,
    "Shooter": 1,
    "Sim": 1,
    "Simulation": 1,
    "Skating": 1,
    "Space": 1,
    "Sport": 1,
    Sports: 2,
    "Stacking": 1,
    "Strategy": 1,
    "Surfing": 1,
    "Survival": 1,
    "Tactical": 1,
    "Tactics": 1,
    "Team": 1,
    "Tennis": 1,
    "Text": 1,
    "Third": 1,
    "Third-Person": 1,
    "Top-Down": 1,
    "Train": 1,
    "Trainer": 1,
    "Trivia": 1,
    "Turn-Based": 1,
    "Tycoon": 1,
    "Vehicle": 1,
    "Vertical": 1,
    "Virtual": 1,
    "Visual": 1,
    "Western": 1,
    "Wrestling": 1,
    // Redirects
    get Baseball() { return this.Sports },
    get Basketball() { return this.Sports },
    get Billiards() { return this.Sports },
    get Bowling() { return this.Sports },
    get Cricket() { return this.Sports },
    get Football() { return this.Sports },
    get Golf() { return this.Sports },
    get Hockey() { return this.Sports },
    get Rugby() { return this.Sports },
    get Soccer() { return this.Sports },
    get Skiing() { return this.Sports },
}
